name: istchrat
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.3+14

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.0.0+2
  flutter_local_notifications: ^9.9.1
  cloud_firestore: ^3.1.7
  firebase_core: ^1.7.2
  firebase_crashlytics: ^2.2.3
  firebase_remote_config: ^2.0.17
  flutter_image_slideshow: ^0.1.2
  firebase_messaging: ^13.0.1
  get: ^4.6.1
  flutter_text_form_field: ^1.0.3
  dependencies:
  carousel_slider: ^4.0.0
  youtube_player_flutter: ^8.1.0
  video_player:
  audio_video_progress_bar: ^0.10.0
  device_preview: ^1.0.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  dio: ^4.0.4
  html: ^0.15.0
  email_validator: ^2.0.1
  dartz: ^0.10.1
  modal_progress_hud_nsn: ^0.3.0
  get_storage: ^2.0.3
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  url_launcher: ^6.0.20
  image_picker: ^0.8.4+11
  agora_rtc_engine: ^5.3.0
  permission_handler: ^10.0.0
  intl: ^0.17.0
  flutter_ringtone_player: ^3.2.0
  country_pickers:
  flutter_windowmanager: ^0.2.0
  lazy_load_scrollview: ^1.3.0
  in_app_purchase: ^3.0.7
  webview_flutter_plus: ^0.3.0+2
  flutter_inappwebview: ^5.7.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  image_path: "assets/images/rounded_logo.png"

dependency_overrides:
  firebase_core_platform_interface: 4.5.1



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/
   - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: GE-SS
      fonts:
        - asset: assets/fonts/font.otf
        - asset: assets/fonts/font.otf
          weight: 500
        - asset: assets/fonts/font.otf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
