import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'hello': 'Hello World',
          "my_account": "My Account",
          "question_and_answer": "Questions And Answers",
          "notifications": "Notifications",
          "change_password": "Change Password",
          "edit_account_information": "Edit Account Information",
          "change_lang": "Change Language",
          "lang": "English",
          "support": "Support",
          "help": "Help",
          "about_app": "About App",
          "explore": "Explore",
          "favourite": "Favourite",
          "my_library": "My Library",
          "account": "Account",
          "recorded_courses": "Recorded Courses",
          "online_courses": "Online  Courses",
          "books_and_writings": "Books And Writings",
          "watch": "Watch",
          "buy_now": "Buy Now",
          "read_the_book": "Read The Book",
          "create_new_account": "Create New Account",
          "create_new_account_text":
              "Create a new account to be able to follow your content",
          "name": "name",
          "email": "Email",
          "phone_number": "Phone Number",
          "password": "Password",
          "sign_up": "Sign Up",
          "by_completing": "By completing, you agree to the",
          "terms_of_use": "Terms of Use",
          "and": "and",
          "privacy_policy": "Privacy Policy",
          "have_account": "I Already Have Account",
          "welcome": "Welcome",
          "login_to_continue":
              "Login into your account to be able to follow your content",
          "forget_password": "Forget Your Password",
          "login": "Login",
          "new_user": "New User",
          "assign_new_password": "Assign New Password",
          "enter_your_email_message":
              "Enter your e-mail, and you will receive a message with a verification code in order to recover your password",
          "send_verification_code": "Send Verification Code",
          "verification_code": "Verification Code",
          "verification_code_sent":
              "A code has been sent to your email, please enter it to set a new password",
          "enter_new_password_message":
              "Please enter a new password, bearing in mind that it is case sensitive",
          "did_not_get_code": "didn`t get code?",
          "resend_code": "Re-send Code Again",
          "verify": "Verify",
          "new_password": "New Password",
          "create_new_password": "New Password",
          "good_day_to_learn": "Today is a great day to learn something new",
          "what_you_need": "What do you need ?",
          "video_consultation": "Video Consultation",
          "audio_consultation": "Audio Consultation",
          "text_conversation": "Text Conversation",
          "appointment_consultation" : "Appointment consultation",
          "book_place": "Book a Place",
          "choose_time": "Choose time",
          "consultation_duration": "Consultation Duration",
          "reserve_consultation": "Reserve Consultation",
          "reserve":"Book Now",
          "coupon_discount": "Use Coupon Hayak to get 20% off",
          "enter_discount_coupon": "Enter discount coupon",
          "validate": "Validate",
          "payment_method": "Payment Method",
          "change": "Change",
          "communication_method": "Communication method",
          "consultation_fees": "Consultation Fees",
          "course_fees":"Course fees",
          "book_fees" : "Book fees",
          "tax": "Tax",
          "total": "Total",
          "confirm_reservation": "Confirm Reservation",
          "statistics": "Statistics",
          "vedioConsultation": "Vedio Consultation",
          "audioConsultation": "Audio Consultation",
          "chatMessage": "Messages",
          "onlineCourse": "Online Courses",
          "registeredCourse": "Registered Courses",
          "books": "Books",
          "Questandanswer": "Question and Answer",
          "bookAppointment": "حجز عيادة",
          "month": "Month",
          "day": "Day",
          "statistics_nav_bar": "Statistics",
          "logs" : "Logs",
          "waiting" : "Waiting",
          "from" : "From",
          "to" : "To",
          "book_details" : "Book Details",
          "book_details_message" : "Upon purchase, it will be available to you",
          "about_the_book" : "About The Book",
          "buy_it" : "Buy it",
          "page_number" : "Pages Number",
          "classification" : "Classification",
          "date_of_publication" : "Date Of Publication",
          "buy_the_book" : "Buy The Book",
          "write_message" : "Write Message",
          "course_details" : "Course Details",
          "course_duration" : "Course Duration",
          "course_date" : "Course Date",
          "last_update" : "Last Update",
          "buy_recorded_course" : "Buy Recorded Course",
          "delay" : "Delay",
          "delay_appointment" : "Delay Appointment",
          "name_validation" : "name can`t be empty",
          "email_validation" : "email can`t be empty",
          "phoneNumber_validation" : "wrong phone number",
          "password_validation" : "password at least 8 digits",
          "password_validation2" : "password can`t be empty",
          "wrong_email" : "wrong email",
          "unauthorized" : "Unauthorized",
          "cancel" : "Cancel",
          "network_error" : "Network Error!",
          "nodata":"No Data",
          "error" : "Error!",
          "istcharat" : "Istcharat",
          "by_period" : "By Period",
          "by_status" : "By Status",
          "filter_results" : "Filter Results",
          "send" : "Send",
          "reject_reason" : "Reject Reason",
          "write_reject_reason" : "Write Reject Reason",
          "reject_reason_validation" : "Reject Reason Can`t be empty",
          "search_with_user_name" : "Search With User Name",
          "write_user_name" : "write name here",
          "search" : "Search",
          "network_error_retry" : "Network Error - Retry Again?!",
          "emergency_consultation" : "Emergency Consultation",
          "question_validation" : "Please Enter Your Question",
          "question_hint_text" : "write your question here and we will reply as soon as possible",
          "continue" : "Continue",
          "what_your_question" : "What Is Your Question?",
          "details" : "Details",
          "wallet_header" : "You have in the wallet",
          "Wallet" : "Wallet",
          "logout" : "Logout",
          "enter_old_password" : "Enter your old password",
          "enter_new_password" : "Enter your new password",
          "enter_new_password_again" : "Enter your new password again",
          "edit" : "Edit",
          "accept" : "Accept",
          "refuse" : "Refuse",
          "start_call" : "Start Call",
          "nodata_in":"No Data In",
          "done" : "Done",
          "thanks" : "Thank You",
          "changed_successfully" : "Info has been updated successfully",
          "unknown_error" : "Something went wrong!",
          "delete_account" : "Delete Account",
          "delete_account_confirmation" : "Are you sure to delete your account ?",
          "delete" : "Delete",
          "contact_us" : "Contact with us",
          "buy_course" : "Buy course",
          "you_should_login_first" : "You should login first",
          "notifications_settings" : "Notifications settings",
          "credit_card" : "Credit Card",
          "wallet" : "Wallet",
          "download_wtsapp" : "Please download Whatsapp first",
          "USD" : "USD",
          "add_to_library" : "Add to My library",
          "added_to_library" : "@product has been added to My library successfully",
          "payment" : "Payment",
          "paid_successfully" : "Payment done successfully",
          "paid_failed" : "Payment has failed",
          "price" : "Price",
          "Today" : "Today",
          "no_notifications" : "No Notifications",
          "password_dont_match" : "Passwords don't match",
          "watch_course" : "Watch course",
          "code_resent" : "Code has been resent",
          "consultation_delayed" : "Consultation delayed",
          "consultation_delayed_description" : "Consultation with @name has been delayed to @date at @time",
          "start_chat" : "Start chat",
          "ok" : "Ok",
          "please_enter_verification_code" : "Please enter verification code",
          "verification_code_length" : "Verification code must be 4 characters",
          "password_changed" : "Password has been changed",
          "Notes" : "Notes",
          "no_notes" : "There is no notes",
          "add_notes" : "Add Notes",
          "add_notes_validation" : "Notes shouldn't be empty",
          "time_zone" : "Kuwait & ksa Timing",
          "lecturer_notes" : "Lecturer's notes",
          "Answer" : "Answer",
          "Question" : "Question",
          "delayed" : "Delayed",
          "discount" : "Discount"
        },
        'ar': {
          'hello': 'أهلا',
          "my_account": "حسابى",
          "question_and_answer": "أسئلة وأجوبه",
          "notifications": "الإشعارات",
          "change_password": "تغيير كلمة المرور",
          "edit_account_information": "تعديل بيانات الحساب",
          "change_lang": "تغيير اللغة",
          "lang": "العربية",
          "support": "الدعم",
          "help": "مساعدة",
          "reserve":"احجز الأن",
          "about_app": "عن التطبيق",
          "explore": "استكشف",
          "favourite": "المفضلة",
          "my_library": "مكتبتى",
          "account": "حسابى",
          "recorded_courses": "الدورات المسجلة",
          "online_courses": "دورات البث المباشر",
          "books_and_writings": "الكتب والمؤلفات",
          "watch": "شاهد الآن",
          "buy_now": "اشتري الآن",
          "read_the_book": "اقرأ الكتاب",
          "create_new_account": "أنشئ حساب جديد",
          "create_new_account_text":
              "أنشئ حساب جديد لكى تتمكن من متابعة المحتوى الخاص بك",
          "name": "الأسم",
          "email": "البريد الالكترونى",
          "phone_number": "رقم الجوال",
          "password": "كلمة المرور",
          "sign_up": "تسجيل الدخول",
          "by_completing": "من خلال استكمال فإنك توافق على",
          "terms_of_use": "شروط الاستخدام",
          "and": "و",
          "privacy_policy": "سياسة الخصوصية",
          "have_account": "لدي حساب بالفعل",
          "welcome": "مرحبا بك",
          "login_to_continue": "قم بتسجيل الدخول لكى تتمكن من متابعة محتواك",
          "forget_password": "نسيت كلمة المرور",
          "login": "تسجيل الدخول",
          "new_user": "مستخدم جديد",
          "assign_new_password": "تعيين كلمة مرور جديدة",
          "enter_your_email_message":
              "ادخل حسابك وسوف تصلك رسالة بها كود التحقق لكى تتمكن من استعادة كلمة المرور الخاصة بك",
          "send_verification_code": "أرسل كود التحقق",
          "verification_code": "كود التحقق",
          "verification_code_sent":
              "لقد تم ارسال الكود الى بريدك الالكترونى يرجى اددخاله من اجل تعيين كلمه مرور جديدة",
          "please_enter_verification_code" : "من فضلك ادخل كود التحقيق",
          "enter_new_password_message":
              "يرجى ادخال كلمة مرور جديدة مع الأخذ فى الاعتبار انها حساسة فى حالة الاحرف",
          "did_not_get_code": "لم تستلم الكود؟",
          "resend_code": "ارسل الكود مرة أخرى",
          "verify": "تحقق",
          "new_password": "كلمة مرور جديدة",
          "create_new_password": "كلمة المرور الجديدة",
          "good_day_to_learn":
              "اليوم يوم عظيم لتعلم شئ جديد",
          "what_you_need": "ماذا تريد ان تفعل",
          "video_consultation": "استشارة فيديو",
          "audio_consultation": "استشارة صوتية",
          "text_conversation": "استشارة نصية",
          "appointment_consultation" : "موعد",
          "book_place": "حجز عيادة",
          "choose_time": "اختر الوقت",
          "consultation_duration": "مدة الاستشارة",
          "reserve_consultation": "احجز للاستشارة",
          "coupon_discount": "استخدم كود حياك للحصول على خصم 20%",
          "enter_discount_coupon": "ادخل كود الخصم",
          "validate": "تفعيل",
          "payment_method": "طريقة الدفع",
          "change": "تغيير",
          "communication_method": "طريقة التواصل",
          "consultation_fees": "رسوم الاستشارة",
          "course_fees":"رسوم الدورة",
          "book_fees" : "رسوم الكتاب",
          "tax": "رسوم إضافية",
          "total": "الاجمالى",
          "confirm_reservation": "تاكيد الحجز",
          "statistics": "إحصائيات الخدمات",
          "vedioConsultation": "استشارات  الفيديو",
          "audioConsultation": "الاستشارات الصوتيه",
          "chatMessage": "الرسائل",
          "onlineCourse": "دورات البث المباشر",
          "registeredCourse": "الدورات المسجلة",
          "books": "الكتب والمؤلفات",
          "Questandanswer": "سؤال وجواب",
          "bookAppointment": "حجز عيادة",
          "month": "الشهر",
          "day": "اليوم",
          "statistics_nav_bar": "إحصائيات",
          "logs" : "السجل",
          "waiting" : "الانتظار",
          "from" : "من",
          "to" : "الى",
          "book_details" : "تفاصيل الكتاب",
          "book_details_message" : "عند الشراء سيكون متاح لك اون لاين",
          "about_the_book" : "عن الكتاب",
          "buy_it" : "قامو بالشراء",
          "page_number" : "عدد الصفحات",
          "classification" : "التصنيف",
          "date_of_publication" : "تاريخ النشر",
          "buy_the_book" : "اشتري الكتاب",
          "write_message" : "أكتب ما تريد",
          "course_details" : "تفاصيل الدورة",
          "course_duration" : "مدة الدورة",
          "course_date" : "تاريخ الدورة",
          "last_update" : "أخر تحديث",
          "buy_recorded_course" : "اشتري الدورة المسجلة",
          "delay" : "تأجيل",
          "delay_appointment" : "تأجيل الموعد",
          "name_validation" : "الأسم لا يجب ان يكون فارغ",
          "email_validation" : "البريد الالكترونى لا يجب ان يكون فارغ",
          "phoneNumber_validation" : "رقم الجوال غير صحيح",
          "password_validation" : "الرقم السرى يجب ان لا يقل عن 8 حروف او ارقام",
          "password_validation2" : "الرقم السرى يجب ان لا يكون فارغ",
          "wrong_email" : "البريد الالكترونى غير صحيح",
          "unauthorized" : "بيانات الدخول غير صحيحة",
          "cancel" : "اغلاق",
          "network_error" : "خطأ بالأنترنت!",
          "nodata":"لا يوجد بيانات حاليا",
          "error" : "خطأ!",
          "istcharat" : "استشارات",
          "by_period" : "حسب الفترة",
          "by_status" : "حسب الحالة",
          "filter_results" : "تصفية النتائج",
          "send" : "ارسال",
          "reject_reason" : "سبب الرفض",
          "write_reject_reason" : "أكتب سبب الرفض",
          "reject_reason_validation" : "سبب الرفض لايمكن أن يكون فارغ",
          "search_with_user_name" : "بحث باسم صاحب الحالة",
          "write_user_name" : "اكتب الاسم هنا",
          "search" : "بحث",
          "network_error_retry" : "خطأ بالأنترنت! - اعادة المحاولة؟!",
          "emergency_consultation" : "استشارات طارئة",
          "question_validation" : "من فضلك أدخل سؤالك",
          "question_hint_text" : "أكتب سؤالك هنا وسوف نرد عليك فى أقرب وقت ممكن",
          "continue" : "متابعة",
          "what_your_question" : "ما هو سؤالك أو استفسارك",
          "details" : "التفاصيل",
          "Wallet" : "المحفظة",
          "wallet_header" : "لديك في المحفظة",
          "logout" : "تسجيل الخروج",
          "enter_old_password" : "أدخل كلمة المرور القديمة",
          "enter_new_password" : "أدخل كلمة المرور الجديدة",
          "enter_new_password_again" : "أدخل كلمة المرور الجديدة مرة أخرى",
          "edit" : "تعديل",
          "accept" : "موافقة",
          "refuse" : "رفض",
          "start_call" : "بدء المكالمة",
          "nodata_in":"لا يوجد بيانات حاليا فى",
          "done" : "تم",
          "thanks" : "شكرا لك",
          "changed_successfully" : "تم تعديل البيانات بنجاح",
          "unknown_error" : "حدث خطأ ما!",
          "delete_account" : "حذف الحساب",
          "delete_account_confirmation" : "هل تريد حذف الحساب نهائيا؟",
          "delete" : "حذف",
          "contact_us" : "تواصل معنا",
          "buy_course" : "التسجيل في الدورة",
          "you_should_login_first" : "يجب ان تقوم بتسجيل الدخول اولا",
          "notifications_settings" : "إعدادات الإشعارات",
          "credit_card" : "البطاقة الائتمانية",
          "wallet" : "المحفظة",
          "download_wtsapp" : "من فضلك قم بتحميل الواتساب",
          "USD" : "دولار",
          "add_to_library" : "اضف الي المكتبة",
          "added_to_library" : "تم اضافة @product الي المكتبة",
          "payment" : "الدفع",
          "paid_successfully" : "تمت عملية الدفع بنجاح",
          "paid_failed" : "حدث خطأ اثناء الدفع",
          "price" : "السعر",
          "Today" : "اليوم",
          "no_notifications" : "لا يوجد إشعارات",
          "password_dont_match" : "كلمة المرور غير متطابقة",
          "Book" : "الكتاب",
          "Course" : "الدورة",
          "watch_course" : "مشاهدة الدوره",
          "code_resent" : "تم إعادة إرسال الكود",
          "consultation_delayed" : "تم تأجيل الاستشارة",
          "consultation_delayed_description" : "تم تأجيل الاستشاره مع @name الى @date في الساعة @time",
          "start_chat" : "بدأ المحادثة",
          "ok" : "حسنا",
          "verification_code_length" : "يجب ان يكون كود التحقيق 4 رموز",
          "password_changed" : "تم تغيير كلمة المرور بنجاح",
          "pending" : "قيد الانتظار",
          "approved" : "تمت الموافقة",
          "rejected" : "مرفوض",
          "delayed" : "مؤجل",
          "Notes" : "ملاحظات",
          "no_notes" : "لا يوجد ملاحظات",
          "add_notes" : "أضف ملاحظات",
          "add_notes_validation" : "لا يجب ان تكون الملاحظات فارغة",
          "time_zone" : "بتوقيت الكويت ومكة المكرمة",
          "lecturer_notes" : "ملاحظات المحاضر",
          "Answer" : "الإجابة",
          "Question" : "السؤال",
          "discount" : "خصم"
        }
      };
}
